#!/bin/bash

set -e

helpers_dir=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)

if [ -z "$DEPENDABOT_NATIVE_HELPERS_PATH" ]; then
  install_dir="$helpers_dir"
else
  install_dir="$DEPENDABOT_NATIVE_HELPERS_PATH/bundler/v2"
  mkdir -p "$install_dir"

  cp -r \
    "$helpers_dir/lib" \
    "$helpers_dir/monkey_patches" \
    "$helpers_dir/run.rb" \
    "$helpers_dir/Gemfile" \
    "$install_dir"
fi

export GEM_HOME=$install_dir/.bundle

git clone --single-branch --depth 1 --branch one-more-fix https://github.com/rubygems/rubygems /tmp/rubygems
(cd /tmp/rubygems/bundler && BUNDLER_SPEC_SUB_VERSION=2.4.0 rake override_version && rake install)
rm -rf /tmp/rubygems

cd "$install_dir"

bundle config --local path.system true

if [ -n "$DEPENDABOT_NATIVE_HELPERS_PATH" ]; then
  bundle config --local without "test"
fi

bundle install
